### ISSUE TITLE
Horizontal 'blob' (single row) breaks fit_ellipse

### ISSUE THREAD

**Issue by pmallas** [idl-coyote/coyote#2]
What steps will reproduce the problem?
1. Obtain an image with a horizontal 'blob' (i.e., single row)
2. Run fit_ellipse on said image
3. Fail
 
Can be reproduced with the following code:
IDL> x = bytarr(64, 64)
IDL> x[10:24, 32] = 1
IDL> res = fit_ellipse(x)
% Compiled module: FIT_ELLIPSE.
% Compiled module: ARRAY_INDICES.
% TOTAL: For input argument ARRAY, Dimension must be 1.
% Execution halted at: FIT_ELLIPSE       157 
....\coyote\fit_ellipse.pro
%                      $MAIN$

**Comment by flamingbear** [comment]
Hi, 

I think you've reported a degenerate case, but I'm not sure you're using the routine properly.  You are passing in the image, and you need to pass in the indices of the blob to which the ellipse should be fit.

I will update the routine to guarantee that the temp array is large enough that it will not crash, but you're still going to get a semi-major axis length of 0 and that will look like a line when over plotted.

Let me know if my change helps at all.

Matt

```idl
pro test_ellipse

   x =  bytarr( 64,  64 )
   x[ 10:24,  32 ] =  1
   indices =  where( x eq 1 )
   res =  fit_ellipse( indices,  xsize = 64,  ysize = 64 )
   Window, XSize = 64, YSize = 64
   TV, x
   PLOTS, res, /Device, Color = cgColor( 'red' )
   print, res
end
```
