### ISSUE TITLE
Ambiguous keyword in cgMap_Grid

### ISSUE THREAD

**Issue by sappjw** [idl-coyote/coyote#28]
9fc0811 introduced a bug that breaks some existing code.  IDL can't distinguish between `LABEL` and `LABEL_WITH_DEGREE` because the former may be a shortened version of the latter.  Since there already exists a `LABEL` keyword there's now a conflict.  The new keyword needs a different start to the name (maybe `DEGREE_LABEL`?).

Reproduce with:

    IDL> cgmap_set, label=1, /grid

    Traceback Report from CGMAP_SET:

         % Ambiguous keyword abbreviation: LABEL.
         % Execution halted at:  CGMAP_SET         617

**Comment by flamingbear** [comment]
Just saw this, thanks for the report.

**Comment by bianbian-org** [comment]
thanks, sorry for my fault
