### ISSUE TITLE
Storing into undefined variable

### ISSUE THREAD

**Issue by fawltylanguage** [idl-coyote/coyote#30]
In cgdisplay.pro at line 287 ps_struct.landscape is used on the LHS, but ps_struct is undefined here.

**Comment by wlandsman** [comment]
When using cgdisplay in postscript, it should be preceded by a call to cgps_open which defines ps_struct in a common block.

**Comment by fawltylanguage** [comment]
Thanks. I thought cgps_open/cgps_close were just convenience routines for set_plot,'ps'/device,/close. 

Not a bug, closed.
